### ISSUE TITLE
setPreviewDefaultOptions无效

### ISSUE THREAD

**Issue by wallace-yang** [zhangchuqiang/vue3-preview-image#3]
![image](https://github.com/zhangchuqiang/vue3-preview-image/assets/45649432/81a62e0f-dad9-4581-aafd-475d98223e7c)

**Comment by zhangchuqiang** [comment]
默认为true，你传了true所以无效呀，你想禁用这两个功能的话要传false

**Comment by wallace-yang** [comment]
> 默认为true，你传了true所以无效呀，你想禁用这两个功能的话要传false

我的意思就是那个默认为true不生效，我点遮罩层并不能关闭，然后我就加了这个函数，加了甚至还报错了
![image](https://github.com/zhangchuqiang/vue3-preview-image/assets/45649432/23f6a54d-743c-4581-9ae6-e8fe3866a159)
setPreviewDefaultOptions是个undefined

**Comment by zhangchuqiang** [comment]
请问版本号是1.2.3吗？

**Comment by wallace-yang** [comment]
> 请问版本号是1.2.3吗？

0.2.7 ，我直接npm i的，我改下版本试试，谢谢

**Comment by wallace-yang** [comment]
> 请问版本号是1.2.3吗？

npm上的最新版就是0.2.7 
![image](https://github.com/zhangchuqiang/vue3-preview-image/assets/45649432/7a564eaf-b10e-4b9d-95c2-7d1d4de375a2)

**Comment by zhangchuqiang** [comment]
你用的不是我的包，我也才看出来.....
你用的是vue3-image-preview，我的是vue3-preview-image

**Comment by wallace-yang** [comment]
> vue3-preview-image

哈哈，我换一下

**Comment by wallace-yang** [comment]
> 你用的不是我的包，我也才看出来..... 你用的是vue3-image-preview，我的是vue3-preview-image

很好用，牛逼
